import sys
p=sys.argv[1]; s=open(p).read()
def rep(a,b):
    global s
    assert s.count(a)==1,a
    s=s.replace(a,b)
rep("""    let old = field(c, offset_of(Thread, cr3))
    let owned = field(c, offset_of(Thread, owns))""","""    let old = field(c, offset_of(Thread, cr3))
    let owned = field(c, offset_of(Thread, owns))
    log.put("dbg exec_current slot ")
    log.dec(c as int)
    log.put(" old ")
    log.hex(old)
    log.put(" owned ")
    log.hex(owned)
    log.put(" new ")
    log.hex(cr3)
    log.put(" free ")
    log.dec(frames.free_count() as int)
    log.put(" stack ")
    log.hex(paging.translate(sv(S_PML4), field(c, offset_of(Thread, stack_hi)) - 8) else 0)
    log.end()""")
rep("""    make_stack(s)
    fpu.fork(p, s)""","""    make_stack(s)
    log.put("dbg clone slot ")
    log.dec(s as int)
    log.put(" top frame ")
    log.hex(paging.translate(sv(S_PML4), field(s, offset_of(Thread, stack_hi)) - 8) else 0)
    log.put(" free ")
    log.dec(frames.free_count() as int)
    log.end()
    fpu.fork(p, s)""")
rep("""        if s != cur() && field(s, offset_of(Thread, state)) == DEAD {
            free_stack(s)""","""        if s != cur() && field(s, offset_of(Thread, state)) == DEAD {
            log.put("dbg reap slot ")
            log.dec(s as int)
            log.put(" cr3 ")
            log.hex(field(s, offset_of(Thread, cr3)))
            log.put(" owns ")
            log.hex(field(s, offset_of(Thread, owns)))
            log.put(" top frame ")
            log.hex(paging.translate(sv(S_PML4), field(s, offset_of(Thread, stack_hi)) - 8) else 0)
            log.end()
            free_stack(s)""")
open(p,'w').write(s)
